### ISSUE TITLE
Followed instructions but crashes

### ISSUE THREAD

**Issue by 3decimal14159** [jainanuj7/file-integrity-blockchain#1]
Hello,
i followed the instructions on the site page and i get 

Error: Cannot find module 'C:\Users\g3decimal14159\Desktop\CipherStamp\index.js'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

can anyone help?

**Comment by 3decimal14159** [comment]
Unable to find a suitable version for angular, please choose one by typing one o
f the numbers below:
    1) angular#1.6.5 which resolved to 1.6.5 and is required by angular-aria#1.6
.5
    2) angular#1.6.10 which resolved to 1.6.10 and is required by angular-animat
e#1.6.10
    3) angular#1.7.8 which resolved to 1.7.8 and is required by angular-animate#
1.7.8, angular-messages#1.7.8, angular-resource#1.7.8
    4) angular#>=1.0.8 which resolved to 1.7.8 and is required by ngGeolocation#
0.0.8, ngstorage#0.3.11
    5) angular#^1.7.2 which resolved to 1.7.8 and is required by loopback-exampl
e-angular#5eef93ae1a
    6) angular#^1.4.8 which resolved to 1.7.8 and is required by angular-materia
l#1.1.4
    7) angular#^1.4.0 which resolved to 1.7.8 and is required by angular-materia
l-data-table#0.10.10
    8) angular#>= 1.2.0 which resolved to 1.7.8 and is required by angular-ui-ro
uter#1.0.22
    9) angular#^1.5.0 which resolved to 1.7.8 and is required by angular-materia
l-sidemenu#1.0.1
    10) angular#^1.2.0 which resolved to 1.7.8 and is required by ngclipboard#2.
0.0

Prefix the choice with ! to persist it to bower.json

**Comment by jainanuj7** [comment]
Try choosing 1.7.x

**Comment by jainanuj7** [comment]
NOTE: Days of efforts of multiple developers went into developing these APIs. Therefore the APIs have not been made public. Drop me an email at lookforaj@gmail.com if you want to have access to the APIs. :)
The missing APIs are the reason why it is crashing at your end.
